//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessControlList
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public string RoleName { get; set; }
    
        public virtual AccessList AccessList { get; set; }
        public virtual RoleInfo RoleInfo { get; set; }
    }
}
