//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessList
    {
        public AccessList()
        {
            this.AccessControlLists = new HashSet<AccessControlList>();
            this.AccessList1 = new HashSet<AccessList>();
        }
    
        public int MenuId { get; set; }
        public string MenuDisplayText { get; set; }
        public string RelativeLink { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ParentMenu { get; set; }
    
        public virtual ICollection<AccessControlList> AccessControlLists { get; set; }
        public virtual ICollection<AccessList> AccessList1 { get; set; }
        public virtual AccessList AccessList2 { get; set; }
    }
}
