//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerImage
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public bool IsActive { get; set; }
        public string Title { get; set; }
        public string BannerDescription { get; set; }
        public Nullable<int> BannerType { get; set; }
    }
}
