//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillOfLading
    {
        public string BillCode { get; set; }
        public string Sender { get; set; }
        public string SenderAddress { get; set; }
        public string SenderContactName { get; set; }
        public string SenderTel { get; set; }
        public System.DateTime SentDate { get; set; }
        public string Receiver { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverTel { get; set; }
        public string DeliveryStaff { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> RetransferTime1 { get; set; }
        public string Reason1 { get; set; }
        public Nullable<System.DateTime> RetransferTime2 { get; set; }
        public string Reason2 { get; set; }
        public string LadingStatus { get; set; }
        public string FailNote { get; set; }
        public string ReceiverContactName { get; set; }
        public string ActualReceiver { get; set; }
        public Nullable<int> Customer { get; set; }
        public bool IsReadOnly { get; set; }
        public string Acceptor { get; set; }
    
        public virtual Customer Customer1 { get; set; }
    }
}
