//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.BillOfLadings = new HashSet<BillOfLading>();
        }
    
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Logo { get; set; }
        public string Website { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string ContactCellPhone { get; set; }
        public string CustomerAddress { get; set; }
    
        public virtual ICollection<BillOfLading> BillOfLadings { get; set; }
    }
}
