//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotLine
    {
        public int Id { get; set; }
        public string LoginName { get; set; }
        public string LineType { get; set; }
        public string DisplayText { get; set; }
    }
}
