//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string PassCode { get; set; }
        public bool IsActive { get; set; }
        public string UserCode { get; set; }
    
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
