//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTGPost.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteDBEntities : DbContext
    {
        public WebsiteDBEntities()
            : base("name=WebsiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HotLine> HotLines { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NewsCategory> NewsCategories { get; set; }
        public DbSet<AccessControlList> AccessControlLists { get; set; }
        public DbSet<AccessList> AccessLists { get; set; }
        public DbSet<RoleInfo> RoleInfoes { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<BannerImage> BannerImages { get; set; }
        public DbSet<BillOfLading> BillOfLadings { get; set; }
        public DbSet<Customer> Customers { get; set; }
    }
}
